#!/usr/bin/python3
import sys

sumvalues = 0
valuecnt = 0
for line in sys.stdin:
	adcvalue = int(line)

	sumvalues += abs(adcvalue - 512)
	valuecnt += 1

print(sumvalues / valuecnt * 256 * 125 / 682)
