#!/usr/bin/python3
import sys
import math
import random

sample_frequency = 479			# Hz
sample_amplitude_rms = float(sys.argv[1])		# Amps RMS
#noise_amplitude = 8			# ADU
noise_amplitude = 0				# ADU

def signalfunction(x):
	"""x is between 0 .. 2 * pi. Output is between -1 and 1"""
	return math.sin(x)
#	return math.sin(x) + (1/3 * math.sin(3 * x))

sample_amplitude = math.sqrt(2) * sample_amplitude_rms
signal_frequency = 50
sample_period = 1 / sample_frequency
signal_period = 1 / signal_frequency
t = 0
for i in range(10000):
	t += sample_period
	periodpt = (t % signal_period) / signal_period * 2 * math.pi
	fncvalue = sample_amplitude * signalfunction(periodpt)

	convout = (fncvalue * 0.625 / 6) + 2.5
	if convout < 0:
		convout = 0
	elif convout > 5:
		convout = 5


	dividerout = convout / 2

	adcsample = round(((dividerout / 2.5) * 0x3ff) + random.gauss(0, noise_amplitude))
	if adcsample < 0:
		adcsample = 0
	elif adcsample > 0x3ff:
		adcsample = 0x3ff
	print(adcsample)
