#!/bin/bash
#
#

pushd .
cd ../helpers/spi_cmd_if/
#./genspicmdif frontpanel.xml
./genspicmdif currentmonitor.xml
cp out/SPISlave.c out/SPISlave.h ../../currentmon/
popd

make -C ../currentmon/ clean all
if [ "$?" != "0" ]; then
	exit 1
fi
./gen_payload ../currentmon/currentmon.bin CurrentMonitor

make clean all
if [ "$?" != "0" ]; then
	exit 1
fi
make program
