#!/usr/bin/python3
import sys
import textwrap
import hashlib

infile = sys.argv[1]
payloadname = sys.argv[2]
cfilename = "Payload%s.c" % (payloadname)
hfilename = "Payload%s.h" % (payloadname)

# Convert data
data = open(infile, "rb").read()
payloadlen = len(data)
datastr = [ "0x%02x" % (c) for c in data ]
datastr = ", ".join(datastr)
datastr = "\t" + "\n\t".join(textwrap.wrap(datastr, 100))

f = open(cfilename, "w")
print("#include <stdint.h>", file = f)
print("#include <avr/pgmspace.h>", file = f)
print(file = f)
print("/* Payload size %d bytes, md5sum %s */" % (payloadlen, hashlib.md5(data).hexdigest()), file = f)
print("const uint8_t payload%s[] PROGMEM = {" % (payloadname), file = f)
print(datastr, file = f)
print("};", file = f)
print(file = f)

f = open(hfilename, "w")
print("#ifndef __PAYLOAD_%s_H__" % (payloadname.upper()), file = f)
print("#define __PAYLOAD_%s_H__" % (payloadname.upper()), file = f)
print(file = f)
print("#include <stdint.h>", file = f)
print("#include <avr/pgmspace.h>", file = f)
print(file = f)
print("#define LEN_PAYLOAD_%s %d" % (payloadname.upper(), payloadlen), file = f)
print("extern const uint8_t payload%s[] PROGMEM;" % (payloadname), file = f)
print(file = f)
print("#endif", file = f)
